### PR TITLE
meteor update all packages

### LINKED ISSUE #212: Update project dependencies
Around every 1-2 sprints, we have been updating all project dependencies. Run `meteor update --all-packages` to get our dependencies updated to the latest compatible versions.

### PR DESCRIPTION
**Pull request by brylie**
Closes #212

### CODE REVIEW

**Comment by bajiat** [comment]
@marla-singer Could you review this PR?

**Comment by marla-singer** [comment]
@brylie I detected the problem.

### Scenario
1.Create an organization and an api
2. Connect api to organization
3. Navigate to this organization and click on api

### Repeat this for two cases
**First case:** `develop`branch
**Second case:** current branch

### Right result as the same in first case
 - API page is opened, no error on console

### Found result in second case
- API page isn't opened, error on browser console

I repeated it twice and have the same results for both case

Found errors on browser console
```
Exception from Tracker recompute function:
TypeError: Cannot set property 'value' of null
  at ElementAttributesUpdater.update (blaze.js?hash=9d08dd7…:1425)
  at Blaze.View.updateAttributes (blaze.js?hash=9d08dd7…:1590)
  at blaze.js?hash=9d08dd7…:1934
  at Function.Template._withTemplateInstanceFunc (blaze.js?hash=9d08dd7…:3746)
  at blaze.js?hash=9d08dd7…:1932
  at Object.Blaze._withCurrentView (blaze.js?hash=9d08dd7…:2273)
  at viewAutorun (blaze.js?hash=9d08dd7…:1931)
  at Tracker.Computation._compute (tracker.js?hash=9f8a0ce…:339)
  at new Tracker.Computation (tracker.js?hash=9f8a0ce…:229)
  at Object.Tracker.autorun (tracker.js?hash=9f8a0ce…:604)
```
```
Exception from Tracker afterFlush function:
TypeError: Cannot read property 'autosave' of undefined
    at Object.autoFormChangeHandler (aldeed_autoform.js?hash=62240ad…:7945)
    at blaze.js?hash=9d08dd7…:3777
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=9d08dd7…:3746)
    at Blaze.View.<anonymous> (blaze.js?hash=9d08dd7…:3776)
    at blaze.js?hash=9d08dd7…:2619
    at Object.Blaze._withCurrentView (blaze.js?hash=9d08dd7…:2273)
    at Blaze._DOMRange.<anonymous> (blaze.js?hash=9d08dd7…:2618)
    at HTMLFormElement.<anonymous> (blaze.js?hash=9d08dd7…:862)
    at HTMLDivElement.dispatch (modules.js?hash=6ed1f11…:7339)
    at HTMLDivElement.elemData.handle (modules.js?hash=6ed1f11…:7151)
```

**Comment by jykae** [comment]
Reviewed. Got same errors no need even to do above steps, errors come from Blaze & Autoform packages. No idea what they mean..

**Comment by jykae** [comment]
Trying to do update locally step by step, first just meteor update, then update packages one by one.

**Comment by jykae** [comment]
@brylie @marla-singer Everything else went fine but when "blaze upgraded from 2.1.9 to 2.2.1", got this crash.

**Comment by jykae** [comment]
Related issue, probably solved in master but fix not released yet.
https://github.com/meteor/blaze/issues/230

**Comment by marla-singer** [comment]
@jykae @brylie Maybe update package to 2.2.0 version?

**Comment by jykae** [comment]
@marla-singer Yep, I discussed with @brylie & open new PR without updating blaze for now.

**Comment by jykae** [comment]
New PR #224 without blaze package update, this can be closed after reviewing & merging.

**Pull request closed without merging**
