### PR TITLE
Required proxy fields

### LINKED ISSUE #104: A new proxy can be added without filling up mandatory information for URL and Elastic Search
# Reproduction step
1. sign in as APINF admin.
2. Go to profile->Proxy
3. Click Add proxy
4. 1st select proxy type without filling other fields. (mandatory fields don't get populate after selecting proxy type)
5. Fill up name and description and save.

# Result:
Proxy can be added without filling mandatory fields (elastic search and URL).
This behavior doesn't occur if fields are filled serially.
proxy

# Expected Result:
no matter what order the fields are filled up, on selecting a proxy from the dropmenu, the mandatory fields should appear in the instant.

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #104
Form saves result without proxy data both apiUmbrella and emqtt type
- Create validation function 
- Checking for validation on before-insert autoform hook
- Delete useless **optional** field in schema (on default _optional: false_)

### CODE REVIEW

**Comment by brylie** [comment]
While this solution is clever and elegant, there may be a [solution that is more aligned with simple schema](https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required). In that approach, the `apiUmbrella` or `emqtt` sub-fields would look at the `proxyType` field and perform validation based on the proxy type selected. This will get [much easier in SimpleSchema v2](https://github.com/aldeed/meteor-simple-schema/issues/618), so lets keep this work relatively close to how Simple Schema is designed to work.

**Comment by brylie** [comment]
Basically, what we are trying to do is **define validation in the schema**.

**Comment by marla-singer** [comment]
@brylie Of course it was my first decision to make validation with simple schema. But we have three independent schemas. `apiUmbrella` and `emqtt` schemas don't know anything about `proxy` schema. We can't use[ this solution](https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required) because we don't know in which moment we must make a field required.

**Comment by brylie** [comment]
Even with multiple sub-schemas, the `proxyType` should be available at the time of validation. I.e. when a document is validated, Simple Schema will be using the combined schema -- despite us breaking it into parts for extensibility.

**Comment by brylie** [comment]
I am willing to merge this solution, if there is no way we can validate closer to the schema. So, lets leave this branch/PR open.

**Comment by marla-singer** [comment]
> Try a quick test to validate or refute the idea, e.g.:
// Inside of custom validation function for emqtt URL field
console.log(this.field('proxyType'));

@brylie Nothing useful
```javascript 
{isSet: false, value: undefined, operator: undefined}
```

**Comment by brylie** [comment]
Ah, sorry. It should have been:

```js
// Inside of custom validation function for emqtt URL field
console.log(this.field('proxyType')).value;
```

**Comment by marla-singer** [comment]
> Did you set a value for the Proxy Type field, via the form?
Sure

**Comment by brylie** [comment]
OK, I am thinking that our schemas don't need to be so complicated for right now. I.e. we are defining them in separate files for modularity, but they are hard coded inside of index.js anyway (in terms of imports and listed within `_.assign()`. Lets move all of the schemas back together inside of `index.js`, that way we can use the custom validation function.

**Pull request merged**
