### PR TITLE
Lint backlog directory

### PR DESCRIPTION
**Pull request by mauriciovieira**
This PR is part of #236 endeavor.

### CODE REVIEW

**Comment by brylie** [comment]
@mauriciovieira is this ready for review?

**Comment by mauriciovieira** [comment]
@Digipalvelutehdas/apika-tiimi please review

**Comment by mauriciovieira** [comment]
@brylie it is now.

**Comment by marla-singer** [comment]
@brylie @mauriciovieira Take it to review

**Pull request merged**
