### PR TITLE
Submit Feedback form working

### PR DESCRIPTION
**Pull request by snittoor**
Bug: Fixed for Feedback submit form. #197

### CODE REVIEW

**Comment by marla-singer** [comment]
Hi @snittoor. If your pull request (PR) is ready for review, you must use the special orange label "Ready for review". It will be known another developers to start reviewing your solution

**Comment by snittoor** [comment]
@marla-singer : Didn't know i had to do it. Will take care of it from next time. Thank you.

**Comment by bajiat** [comment]
@marla-singer Could you review this?

**Comment by marla-singer** [comment]
@bajiat Yep, self-assigned

**Comment by marla-singer** [comment]
@snittoor Good job :-1: It works as expected. Merge it

**Comment by bajiat** [comment]
Thanks for quick review @marla-singer

**Pull request merged**
