### PR TITLE
Connect api from settings tab

### LINKED ISSUE #158: Connect API to an organization from API settings
If the current user is both organization manager and the owner of current API, the user needs to be able to connect the current API to an organization the user is managing. API settings should contain a field to connect API to organization and that field should only be conditionally available.

# Definition of done
* [x] An API owner can see a Connect API to an organization setting in Settings tab, if he also has the role of organization manager
* [x] The available choices for organizations to connect to are organization(s) the current user manages
* [x] If the user selects and organization and saves the changes, a connection between API and organization is made

# Wireframes
1. From API profile's settings tab, API manager can see a dropmenu that contains organizations that s/he manages. API manager can select one of the organization to connect her/his API to it. The dropmenu appears under Details pane.
apisettings1
The following text should appear below the dropmeu (sorry not included in the wireframe).
You can connect your API to one of the organizations that you manage. Afterwards your API will appear in the organization profile. You can connect your API to only one organization only.

2. On selecting an organization and clicking Save, API manager gets an S-alert informing that the API is now connected to the organization and s/he can view the API in the organization profile.
apisettingsadmin

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #158 
- Change publication
- Rename helper
- Add notification for Details block in Settings tab

Blocked by #160

### CODE REVIEW

**Comment by marla-singer** [comment]
@bajiat This solution is ready for review. But if "organizationId" is removed from apis collection (in task №160) then I will have to remade solution because it has strong dependeces on these field

**Comment by jykae** [comment]
@marla-singer please check/pull api - organization relationship changes from develop, PR #182

**Comment by jykae** [comment]
@marla-singer I took further changes to separate PR #195

**Comment by bajiat** [comment]
Closing the PR, since @jykae is continuing in #195.

**Pull request closed without merging**
