### PR TITLE
Feature/use flow router

### PR DESCRIPTION
**Pull request by jykae**
Closes https://github.com/apinf/platform/issues/1234

## Proposed changes
- switch from Iron Router to Flow Router
- replace UniUtils with Flow Router reactive functions getParam/setParams
- add back missing styling for content-wrapper

### CODE REVIEW

**Comment by marla-singer** [comment]
@jykae After Sing out it's redirect to Catalog but URL is still has "sight-out" path.
I don't know if it's glaring error or not, just observation

**Comment by marla-singer** [comment]
Template "404 Error" doesn't work as expected.
### Steps
Navigate to <your_dmain>/api/notFound
### Found error:
`There is no route for the path: notFound`

**Comment by jykae** [comment]
@marla-singer good finds, fixing..

**Comment by jykae** [comment]
@marla-singer fixes ready

**Comment by marla-singer** [comment]
On check

**Comment by marla-singer** [comment]
Good. Merge it

**Pull request merged**
