### PR TITLE
Initial REST API

### LINKED ISSUE #15: API to list APIs
As developer I want to be able to list APIs from catalogue via REST API. Meta information needed: 
- Name
- Organisation
- URL for profile in APIKA catalogue
- description
- Logo url 
- tags/keywords

### LINKED ISSUE #108: Initial structure for REST API
- GET endpoints (all, one)
- initial swagger config
- meta
- tags
- path params

### PR DESCRIPTION
**Pull request by jykae**
Closes #108 

## For reviewer
- SimpleHTTPServer is handy for reviewing API with Swagger UI, clone it first & then server folder "dist" with command "python -m SimpleHTTPServer"
- type URL to http://localhost:3000/rest-api/v1/swagger.json & Explore
- to check quality of Swagger document, validate eg. http://bigstickcarpet.com/swagger-parser/www/index.html (copy&paster swagger.json)

### CODE REVIEW

**Comment by bajiat** [comment]
@marla-singer Can I assign you to review this PR? It is not ready for review yet.

**Comment by marla-singer** [comment]
@bajiat Sure
@jykae Could you please write to steps how to test your work after finishing task?

**Comment by jykae** [comment]
@marla-singer yes, I will.
@brylie requested to put the stuff in several PRs, so I propose here just initial GET routes with generated swagger, without authentication. If overriding action() function is wanted to enhance fields returned etc, we'll do it in separate PR.

**Comment by jykae** [comment]
@marla-singer "python -m SimpleHTTPServer" is handy for checking visual look of generated Swagger.

nayttokuva 2016-12-08 kello 15 20 19

I think initial part is ready for review.

**Comment by marla-singer** [comment]
@brylie I tested it and don't have any recommendation. What about you?

**Comment by brylie** [comment]
Looks good.

**Comment by jykae** [comment]
@brylie @marla-singer could this be merged then?

**Pull request merged**
